version: 2.1
jobs:
  development:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.16.3 
      # Specify service dependencies here if necessary
      - image: circleci/mongo:4.2.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      # change node enviroment and       
      - run: NODE_ENV=development yarn install --pure-lockfile
      # Install dependencies
      - run: yarn install
      # Save downloaded cache for future refresh
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
      - run: echo Build successfully.
workflows:
  version: 2.1
  nest-mongodb:
    jobs:
      - development:
          # filter branch and change branch for push code for test job
          filters:
              branches:
                only: master